### ISSUE TITLE
same sub-group name in group of groups

### ISSUE THREAD

**Issue by pijpe00** [ansible/proposals#160] opened 2019-03-29 12:14 UTC
# Proposal: same sub-group name in group of groups

*Author*: Edwin <@yourGHid> IRC: handle (if different)

*Date*: 2018-MM-DD

- Status: New
- Proposal type: core design
- Targeted release: 2.8
- Associated PR: 
- Estimated time to implement: <X days, weeks, etc.>

## Motivation
Within my playbook I want to change some webserver setting in a particular location. When that is working alright I want to do the same things in another location. Therefore I want to use group of groups, where the subgroup has the same name as on other locations. 

 

### Problems
Depending in which group the playbook is started usa or europe the group webservers consists of (Europe) europehost1 and europhost2 or (usa) usahost1 and usahost2. So you can make your playbooks more global.

## Solution proposal
The request is the groups with the same names under antother group will not be merged as one. Depending in which group the playbook is started usa or europe the group webservers consists of (Europe) europehost1 and europhost2 or (usa) usahost1 and usahost2

```hosts
all:
  children:
    usa:
      children:
        webservers:
          hosts:
            usahost1:
            usahost2:
    europe:
      children:
        webservers:
          hosts:
            europehost1:
            europehost2:
```

**Comment by agaffney** [comment] 2019-03-29 12:25
The problem is that there's no support for group hierarchies, despite the inventory making it look that way. There's only a single group namespace, which is why identically named "child" groups get merged.

How are you expecting to access a separate but identically named group in your playbook? You would need some special syntax, such as `europe:&webservers`, which already works to get hosts that are in both the `europe` and `webservers` group, even with the current behavior.

**Comment by pijpe00** [comment] 2019-03-29 14:05
Do I have in that case for example put the webserver host in two groups? like your example in europe and webservers?

**Comment by agaffney** [comment] 2019-03-29 15:27
That should already be happening in your example inventory.

**Comment by pijpe00** [comment] 2019-03-29 18:13
In my case I have to write a host once and is a member of two groups because the host is automatically a member of his parent group. But also in my case are the usahost1 and usahost2 of europe, because of the same groupname "webservers'.. My question is will your solution work?
I think in your solution I have to make the following host file:
all:
  children:
    usa:
	  hosts:
		usahost1:
		usahost2:
    europe:
	  hosts:
		europehost1:
		europehost2:
	webservers:
          hosts:
            usahost1:
            usahost2:
			europehost1:
            europehost2:

In that case I have to  write two times the hosts (in the location group and the webservers group)
Am I right?

If I am right, I think I can ask for a new feature request, like
I want to know which "active group" I executed the playbook with. In that case I can change the host file like this:
all:
  children:
    usa:
      children:
        usa-webservers:
          hosts:
            usahost1:
            usahost2:
    europe:
      children:
        europe-webservers:
          hosts:
            europehost1:
            europehost2:

In a playbook I can write the following:
- set_fact:
     webserver: "{{ active-group}}-webservers"

- debug:
     msg: "webserver hosts are {{groups[webservers]}}""
 
what do you think about this solution?

**Comment by bcoca** [comment] 2019-04-04 15:39
closing as per vote in  irc meeting, see ticket above for logs, we will post longer explanation/reasoning here.

**Closed by bcoca** 2019-04-04 15:39 UTC
